### ISSUE TITLE
Create Cart History

### ISSUE THREAD

**Issue by PrinceLunga** [PrinceLunga/PatienceOS#7]
Please add Users_Cart_History table and Implement the CRUD, this table should be a copy of Carts Table, the column discount must be removed and the column DateCreated Must be renamed to DateRecorded.

Component to be affected by this change

-MvcInterface
-POSS
-POSS.DataAccess
-POSS.Models
-POSS.Service

EE :  2 days

**Comment by VillakaziCreator** [comment]
Created the cart history functionality
